version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: pip
    directory: /.github/requirements
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: npm
    directory: /control
    schedule:
      interval: weekly
    labels: [dependencies]
